@echo Setting up the environment...
@echo Installing required packages...
conda create -f environment.yml -n solar-perf-intel -y
@echo Activating the environment...
conda activate solar-perf-intel
@echo Environment setup complete. You can now run the application using run_app.bat.